name: lunabase CI

on:
  push:
    branches: master
    tags: v*
  pull_request:
    branches: master
    tags: v*

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LightGBM
        run: |
          cd ${HOME}
          brew install cmake
          brew install libomp
          git clone --recursive https://github.com/microsoft/LightGBM 
          cd LightGBM
          mkdir build
          cd build
          cmake ..
          make -j4
      - name: Install fftw
        run: |
          cd $HOME
          wget http://www.fftw.org/fftw-3.3.8.tar.gz
          tar -xzvf fftw-3.3.8.tar.gz
          cd fftw-3.3.8
          ./configure --prefix=${HOME}/fftw-3.3.8/
          make
          make install
          cd ${GITHUB_WORKSPACE}
      - name: Make
        run: |
             cp ${HOME}/LightGBM/lib_lightgbm.so .
             make ARCH=MAC FFTW=${HOME}/fftw-3.3.8 LGBM=1 LGBM_PATH=${HOME}/LightGBM
             install_name_tool -add_rpath  @executable_path/. ./luna
             install_name_tool -add_rpath  @executable_path/. ./destrat
             install_name_tool -add_rpath  @executable_path/. ./behead
             otool -l ./luna
             tar cvzf mac-luna.tar.gz luna destrat behead
      - uses: actions/upload-artifact@v2
        with:
          name: mac-luna.tar.gz
          path: mac-luna.tar.gz
